bot_account = "kuvibot"
channel = "kuviboy"

[fff]
ask = "veldak"

[[pushup_rewards]]
title = "10 pushups"
pushups = 10

[[pushup_rewards]]
title = "50 pushups"
pushups = 50

[[text_commands]]
alias = "!commands"
text = "See here: https://github.com/kuviman/kuvibot"

[[text_commands]]
alias = "!mods"
text = "StatsGUI, Disco Science, Manual Inventory Sorting"

[[text_commands]]
alias = "!vods"
text = "All streams are archived here: https://www.youtube.com/@kuviVODs"

[[text_commands]]
alias = "!discord"
text = "Join the discord! https://discord.gg/qPuvJ3fT7u"

[[text_commands]]
alias = "!donate"
text = "Feel free to donate here: https://www.donationalerts.com/r/kuviboy"

[[text_commands]]
alias = "!lurk"
text = "lurk mode activated"

[[text_commands]]
alias = "!unlurk"
text = "lurk mode deactivated"

[[text_commands]]
alias = "!os"
text = "I use Nix BTW - https://nixos.org/"

[[text_commands]]
alias = "!rules"
text = "Ribbon world preset, but height is 9"

[[text_commands]]
alias = "!bot"
text = "Here's my source code: https://github.com/kuviman/kuvibot"

[[text_commands]]
alias = "!man"
text = "alt account that is about programming (Rust): https://twitch.tv/kuviman"

[[text_commands]]
alias = "!boy"
text = "alt account that is about gaming (Factorio): https://twitch.tv/kuviboy"
